services:
  whanjeab:
    container_name: whanjeab
    build: .
    restart: always
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm start"
    networks:
      - dev_network
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "3015:3001"

networks:
  dev_network:
    external: true

volumes:
  db-data:
