name: Pulling and Deployments

on:
    push:
        branches: [ main ]



jobs:
    whanjeabs:
        runs-on: self-hosted
        steps:
            - name: whanjeabs pulling and deploy
              run: |
               sudo bash -c"
                  pwd
                  cd /root/whanjeab-server
                  docker ps
                "